commits_history_auxillaries:
  legend:
    enabled: false
  scrollbar:
    enabled: true
  navigator:
    enabled: true
  rangeSelector:
    enabled: true
no_auxillaries:
  scrollbar:
    enabled: false
  navigator:
    enabled: false
  rangeSelector:
    enabled: false
  legend:
    enabled: false

commits_history:
  title: 'Commits'
  tooltip:
    dateFormat: '%B %Y'
  series:
    - name: 'Commits'
      id: 'commits'
    - name: 'Current Month'
      type: 'scatter'
      color: 'rgba(119, 152, 191, 3)'
      marker:
        radius: 4
        symbol: 'circle'

code_history:
  chart:
    defaultSeriesType: 'area'
  title: 'Total Lines'
  plotOptions:
    area:
      stacking: 'normal'
  series:
    - name: 'Code'
      color: '#482268'
      id: 'code'
    - name: 'Comments'
      color: '#008893'
    - name: 'Blanks'
      color: '#99dde3'
  tooltip:
    shared: true

committer_history:
  title: 'Contributors'
  tooltip:
    dateFormat: '%B %Y'
  series:
    - name: 'Committers'
      id: 'committers'
    - name: 'Current Month'
      type: 'scatter'
      color: 'rgba(119, 152, 191, 3)'
      marker:
        radius: 4
        symbol: 'circle'

language_history:
  title: 'Lines'

lines_of_code:
  chart:
    marginLeft: 0
  legend:
    enabled: true
    layout: 'horizontal'
    align: 'center'
    verticalAlign: 'bottom'
    x: 0
    y: 0
    floating: false
    backgroundColor: '#ffffff'
    symbolRadius: 0
  tooltip:
    split: false

