chart:
  defaultSeriesType: 'bar'
credits:
  enabled: false
title:
  text:
xAxis:
  labels:
    align: 'center'
    style:
      fontSize: '0.9em'
      width: '75px'
  gridLineWidth: 0
  lineWidth: 0
yAxis:
  min: 0
  title:
    text: '% of Commits'
  stackLabels:
    enabled: false
  lineWidth: 1
  gridLineWidth: 0
tooltip:
  commit_volume_chart: true
legend:
  align: 'left'
  verticalAlign: 'bottom'
  x: 0
  y: 0
  floating: false
  backgroundColor: 'white'
  borderColor: 'white'
  shadow: false
  layout: 'horizontal'
  itemWidth: 200
  lineHeight: 20
  margin: 20
  padding: 15
  width: 410
  itemStyle:
    fontSize: '0.9em'
plotOptions:
  series:
    states:
      inactive:
        opacity: 1
    stacking: 'percent'
    dataLabels:
      enabled: false
exporting:
  enabled: false
