chart:
  type: 'pie'
  renderTo: 'demographics_chart'
  plotShadow: false
  styledMode: true
title:
  text:
  align: 'right'
  y: 60
  floating: 'true'
  style:
    color: '#000'
    fontSize: '10pt'
tooltip:
  formatter: ''
  style:
    fontSize: '11pt'
    padding: '8px'
plotOptions:
  pie:
    allowPointSelect: true
    cursor: 'pointer'
    innerSize: 80
    slicedOffset: 10
    borderColor: '#fff'
    borderWidth: 0
    dataLabels:
      enabled: true
      minSize: 1
      color: '#000000'
      connectorColor: '#000000'
      format: '<b>{point.name}</b>: {point.y} %'
credits:
  enabled: false
series: [{type: 'pie'}]
exporting:
  enabled: false
