chart:
  type: 'column'
  renderTo: 'vulnerability_version_chart'
  backgroundColor: 'transparent'
  styledMode: true
credits:
  enabled: false
title:
  text: null
  align: 'left'
  useHTML: true
legend:
  horizontalAlign:  'center'
yAxis:
  min: 0
  allowDecimals: false
  title:
    text: 'Vulnerabilities'
    style:
      fontWeight: 'bold'
  stackLabels:
    enabled: false
    style:
      fontWeight: 'bold'
      color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
xAxis:
  type: 'category'
  labels:
    rotation: -45
tooltip:
  headerFormat: '<b>{point.x}</b><br/>'
  pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
plotOptions:
  column:
    stacking: 'normal'
    dataLabels:
      enabled: false
      color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
      style:
        textShadow: '0 0 3px black'
series: []
exporting:
  enabled: false
