reviews:
  options:
    -
     - Most Helpful
     - helpful
    -
     - Recently added
     - recently_added
    -
     - Highest rating
     - highest_rated
    -
     - Lowest rating
     - lowest_rated
  default:
    helpful

project_users:
  options:
    -
     - Name
     - name
    -
     - Kudo Rank
     - kudo_position
  default:
    kudo_position

people:
  options:
    -
     - Kudo Rank
     - kudo_position
    -
     - Name
     - effective_name
  default:
    kudo_position

api_keys:
  options:
    -
     - Most Recent Request
     - most_recent_request
    -
     - Requests Today
     - most_requests_today
    -
     - All-Time Requests
     - most_requests
    -
     - Account
     - account_name
    -
     - Newest Keys
     - newest
    -
     - Oldest Keys
     - oldest

posts:
  options:
    -
     - Newest
     - newest
    -
     - Relevance
     - relevance
    -
     - Unanswered
     - unanswered

projects:
  options:
    -
      - Activity Level
      - activity_level
    -
      - Users
      - users
    -
      - Newest on the Open Hub
      - new
    -
      - Rating
      - rating
    -
      - Relevance
      - relevance
    -
      - Current Contributors
      - active_committers
  default:
    relevance

contributions:
  options:
    -
      - All Time Commits
      - commits
    -
      - 12 Month Commits
      - twelve_month_commits
    -
      - KudoRank
      - kudo_position
    -
      - Language
      - language
    -
      - Name
      - name
    -
      - Recently Active
      - latest_commit
    -
      - Newest Contributors
      - newest
    -
      - Oldest Contributors
      - oldest

enlistments:
  options:
    -
      - Repository Type
      - by_type
    -
      - Url
      - by_url
    -
      - Module Name
      - by_module_name
  default:
    by_url

languages:
  options:
    -
      - Code Lines
      - code
    -
      - Comment Ratio
      - comment_ratio
    -
      - Commits
      - commits
    -
      - Contributors
      - contributors
    -
      - Name
      - name
    -
      - Projects
      - projects
    -
      - Total Lines
      - total
  default:
    name

organizations:
  options:
    -
      - Recently Created
      - newest
    -
      - Name
      - name
    -
      - Number of Projects
      - projects
  default:
    projects
